2025-09-24 18:22:45,631 [PID 54653] DEBUG Using selector: EpollSelector
2025-09-24 18:22:45,631 [PID 54653] INFO Reading Pyre server configurations...
2025-09-24 18:22:45,632 [PID 54653] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
           ^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
2025-09-24 18:58:35,284 [PID 59344] DEBUG Using selector: EpollSelector
2025-09-24 18:58:35,284 [PID 59344] INFO Reading Pyre server configurations...
2025-09-24 18:58:35,285 [PID 59344] ERROR Uncaught error in persistent.run
Traceback (most recent call last):
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/persistent.py", line 299, in run
    return asyncio.get_event_loop().run_until_complete(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/persistent.py", line 224, in run_persistent
    initial_server_options = pyre_server_options.read_server_options(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/pyre_server_options.py", line 129, in read_server_options
    return server_options_reader()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/pyre_server_options.py", line 114, in read
    return PyreServerOptions.create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/pyre_server_options.py", line 93, in create
    start_arguments = start.create_server_arguments(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/commands/start.py", line 311, in create_server_arguments
    source_paths = backend_arguments.get_source_path_for_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/backend_arguments.py", line 418, in get_source_path_for_server
    return get_source_path(
           ^^^^^^^^^^^^^^^^
  File "/home/nguyencodervn02/.local/share/nvim/mason/packages/pyre/venv/lib/python3.12/site-packages/pyre_check/client/backend_arguments.py", line 397, in get_source_path
    raise configuration_module.InvalidConfiguration(
pyre_check.client.configuration.exceptions.InvalidConfiguration: Invalid configuration: Cannot find any source files to analyze. Either `source_directories` or `targets` must be specified.
